parameters:
#    ymc_how_to_service_container.example.class: Ymc\HowToServiceContainerBundle\Example

services:
#    ymc_how_to_service_container.example:
#        class: %ymc_how_to_service_container.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
